export const catalogos = [
  { name: "AREA" },
  { name: "CITY" },
  { name: "COSTCENTER" },
  { name: "COUNTRIES" },
  { name: "CURRENCY" },
  { name: "DEPARTMEN" },
  { name: "DISCRETIONARYTYPE" },
  { name: "EMPLOYEEROL" },
  { name: "EMPLOYEETYPE" },
  { name: "HOURBANKTYPE" },
  { name: "IDENTIFICATIONTYPE" },
  { name: "INDUSTRYSUBTYPE" },
  { name: "INDUSTRYTYPE" },
  { name: "POSITION" },
  { name: "PRODUCTTYPE" },
  { name: "PROJECTCATEGORY" },
  { name: "PROJECTSTATE" },
  { name: "PROJECTTASKSTATE" },
  { name: "PROJECTTASKTYPE" },
  { name: "PROJECTTYPE" },
  { name: "STATES" },
];
